<a href="https://colab.research.google.com/github/HayateSato/DS_Practice/blob/main/Learning_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)
list_a

print(tensor_a)

# Display the tensor device
print(tensor_a.device)

# Display the tensor data type
print(tensor_a.dtype)

tensor([1, 2, 3, 4])
cpu
torch.int64


### Tensor can be calculated like numpy array

In [9]:
array_a = [1, 2, 3, 4]
array_b = [5, 6, 7, 8]

# Create two tensors from the arrays
tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)
print(f"a: {tensor_a}")
print(f"b: {tensor_b}")

# Subtract tensor_b from tensor_a
tensor_c = tensor_a - tensor_b
print(f"c: {tensor_c}")

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b
print(f"d: {tensor_d}")

# Add tensor_c to tensor_d
tensor_e = tensor_c + tensor_d
print(f"e: {tensor_e}")

# concatenating
tensor_f = torch.cat((tensor_a, tensor_b))
print(f"f: {tensor_f}")

a: tensor([1, 2, 3, 4])
b: tensor([5, 6, 7, 8])
c: tensor([-4, -4, -4, -4])
d: tensor([ 5, 12, 21, 32])
e: tensor([ 1,  8, 17, 28])
f: tensor([1, 2, 3, 4, 5, 6, 7, 8])


#### Nueral Netowork

In [11]:
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])  ### if you want to defin a tensor direclty without using a variable, you need double [[ ]]

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(
    nn.Linear(8, 1),
    nn.Linear(1, 1)
                     )

output = model(input_tensor)
print(output)

tensor([[0.0393]], grad_fn=<AddmmBackward0>)


### sigmoid function

In [12]:
input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

tensor([[0.6900]])


### softmax function

In [13]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax()
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1553: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
