<a href="https://colab.research.google.com/github/HayateSato/DS_Practice/blob/main/Learning_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)
list_a

print(tensor_a)

# Display the tensor device
print(tensor_a.device)

# Display the tensor data type
print(tensor_a.dtype)

tensor([1, 2, 3, 4])
cpu
torch.int64


### Tensor can be calculated like numpy array

In [33]:
array_a = [1, 2, 3, 4]
array_b = [5, 6, 7, 8]

# Create two tensors from the arrays
tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)
print(f"a: {tensor_a}")
print(f"b: {tensor_b}")

# Subtract tensor_b from tensor_a
tensor_c = tensor_a - tensor_b
print(f"c: {tensor_c}")

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b
print(f"d: {tensor_d}")

# Add tensor_c to tensor_d
tensor_e = tensor_c + tensor_d
print(f"e: {tensor_e}")

# concatenating
tensor_f = torch.cat((tensor_a, tensor_b))
print(f"f: {tensor_f}")

a: tensor([1, 2, 3, 4])
b: tensor([5, 6, 7, 8])
c: tensor([-4, -4, -4, -4])
d: tensor([ 5, 12, 21, 32])
e: tensor([ 1,  8, 17, 28])
f: tensor([1, 2, 3, 4, 5, 6, 7, 8])


#### Nueral Netowork

In [34]:
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])  ### if you want to defin a tensor direclty without using a variable, you need double [[ ]]

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(
    nn.Linear(8, 1),
    nn.Linear(1, 1)
                     )

output = model(input_tensor)
print(output)

tensor([[0.3729]], grad_fn=<AddmmBackward0>)


at the end of the nn, you need to activate it by calling a function such as
- Sigmoid
- Softmax
- ReLU
- LU
etc.

**Sigmoid is used for binary classification methods where we only have 2 classes, while SoftMax applies to multiclass problem**

### sigmoid function

In [35]:
input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

tensor([[0.6900]])


In [36]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
    nn.Linear(11, 4),
    nn.Linear(4,3),
    nn.Linear(3,2),
    nn.Linear(2,1),
    nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.4793]], grad_fn=<SigmoidBackward0>)


### softmax function

In [37]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax()
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1553: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


In [38]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4),
  nn.Softmax()
)

output = model(input_tensor)
print(output)

tensor([[0.0804, 0.1197, 0.0484, 0.7515]], grad_fn=<SoftmaxBackward0>)


## Hot Encoding
One-hot encoding is a technique that turns a single integer label into a vector of N elements, where N is the number of classes in your dataset

 how to this encoding compare with / without pytorch.
    1. first without
    2. then with pytorch

In [39]:
# without using pytorch
import numpy as np
import torch.nn.functional as F

y = 1
num_classes = 3

# Create the one-hot encoded vector using NumPy
one_hot_numpy = np.array([0, 1, 0])

# Create the one-hot encoded vector using PyTorch
one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes)

print(one_hot_numpy)
print(one_hot_pytorch)

[0 1 0]
tensor([0, 1, 0])


In [40]:
import torch
import torch.nn.functional as F
from torch.nn import CrossEntropyLoss

y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])
num_scores_tensors = scores.shape[1]

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), num_classes = num_scores_tensors)  ### converting the result of y into one-hot encoded vector to save it

# Create the cross entropy loss function
criterion = CrossEntropyLoss()

# Calculate the cross entropy loss
loss = criterion(scores.double(), one_hot_label.double())
print(loss)


print(scores)
print(one_hot_label)
print(criterion)

tensor(8.0619, dtype=torch.float64)
tensor([[ 0.1000,  6.0000, -2.0000,  3.2000]])
tensor([[0, 0, 1, 0]])
CrossEntropyLoss()


In [44]:
criterion = nn.CrossEntropyLoss()

# Calculate the loss
loss = criterion(scores, torch.tensor(y))

# Compute the gradients of the loss
loss.backward()

# Display gradients of the weight and bias tensors in order
# print(weight.grad)
# print(bias.grad)

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [50]:
criterion = nn.CrossEntropyLoss()

weight =  torch.randn(2, 9, requires_grad=True)
bias = torch.randn(2, requires_grad=True)
preds = torch.randn(1, 2, requires_grad=True)
target = torch.tensor([[1.0, 0.0]], requires_grad=False)

# Calculate the loss
loss = criterion(preds, target)

# Compute the gradients of the loss
loss.backward()

# Display gradients of the weight and bias tensors in order
print(weight.grad)
print(bias.grad)

None
None


In [55]:
### each layer parameter can be accessed by indexing the created model directly

model = nn.Sequential(nn.Linear(16, 8),
                      nn.Sigmoid(),
                      nn.Linear(8, 2))

# Access the weight of the first linear layer
weight_0 =  model[0].weight

# Access the bias of the second linear layer
bias_1 = model[2].bias

print(model)
# Sequential(
#   (0): Linear(in_features=16, out_features=8, bias=True)
#   (1): Sigmoid()
#   (2): Linear(in_features=8, out_features=2, bias=True)
# )



Sequential(
  (0): Linear(in_features=16, out_features=8, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=8, out_features=2, bias=True)
)


In [60]:
import torch.optim as optim

# Create the optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)

loss = criterion(preds, target)
loss.backward()

# Update the model's parameters using the optimizer
optimizer.step()