<a href="https://colab.research.google.com/github/HayateSato/DS_Practice/blob/main/Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Number of Samples:
  - Training set: 60,000 images
  - Test set: 10,000 images

- Image Dimensions:
  - Each image is 28x28 pixels in grayscale.

- Classes:
  - The dataset is labeled into 10 classes, representing the digits from 0 to 9.
  - The image has numbers from 0 to 9
- Format:
  - Each image is stored as a 2D numpy array of shape (28, 28), and labels are stored as integers corresponding to the digit shown in the image.


In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models, datasets

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0  # Normalize pixel values



# Define the model architecture
model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),  # Input layer to flatten the images / flattening the matrix into 784 rows
    layers.Dense(128, activation='relu'),  # Hidden layer with ReLU activation 784 --> 128
    layers.Dense(64, activation='sigmoid'),  # Hidden layer with Sigmoid activation
    layers.Dense(10, activation='softmax')  # Output layer with Softmax activation for classification
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5, batch_size=32)

# Evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print(f'\nTest accuracy: {test_acc}')


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8422 - loss: 0.6145
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9612 - loss: 0.1310
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9766 - loss: 0.0798
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9826 - loss: 0.0580
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9879 - loss: 0.0422
313/313 - 1s - 2ms/step - accuracy: 0.9760 - loss: 0.0783

Test accuracy: 0.9760000109672546


In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models, datasets

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0  # Normalize pixel values



# Define the model architecture
model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),  # Input layer to flatten the images / flattening the matrix into 784 rows
    layers.Dense(500, activation='relu'),  # Hidden layer with ReLU activation 784 --> 128
    layers.Dense(64, activation='sigmoid'),  # Hidden layer with Sigmoid activation
    layers.Dense(10, activation='softmax')  # Output layer with Softmax activation for classification
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5, batch_size=32)

# Evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print(f'\nTest accuracy: {test_acc}')


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 21s 10ms/step - accuracy: 0.8776 - loss: 0.4689
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.9738 - loss: 0.0900
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.9843 - loss: 0.0539
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.9899 - loss: 0.0341
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 8ms/step - accuracy: 0.9931 - loss: 0.0236
313/313 - 1s - 4ms/step - accuracy: 0.9788 - loss: 0.0664

Test accuracy: 0.9787999987602234


In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models, datasets

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0  # Normalize pixel values



# Define the model architecture
model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),  # Input layer to flatten the images / flattening the matrix into 784 rows
    layers.Dense(500, activation='relu'),  # Hidden layer with ReLU activation 784 --> 128
    layers.Dense(64, activation='sigmoid'),  # Hidden layer with Sigmoid activation
    layers.Dense(10, activation='softmax')  # Output layer with Softmax activation for classification
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5, batch_size=16)

# Evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print(f'\nTest accuracy: {test_acc}')


Epoch 1/5
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 25s 6ms/step - accuracy: 0.8976 - loss: 0.3978
Epoch 2/5
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 23s 6ms/step - accuracy: 0.9748 - loss: 0.0834
Epoch 3/5
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 41s 6ms/step - accuracy: 0.9825 - loss: 0.0562
Epoch 4/5
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 41s 6ms/step - accuracy: 0.9898 - loss: 0.0347
Epoch 5/5
3750/3750 ━━━━━━━━━━━━━━━━━━━━ 25s 7ms/step - accuracy: 0.9917 - loss: 0.0255
313/313 - 1s - 2ms/step - accuracy: 0.9790 - loss: 0.0712

Test accuracy: 0.9789999723434448


DIfferent commbination of activation functions
=====================

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models, datasets

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0  # Normalize pixel values



# Define the model architecture
model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),  # Input layer to flatten the images / flattening the matrix into 784 rows
    layers.Dense(128, activation='sigmoid'),  # Hidden layer with ReLU activation 784 --> 128
    layers.Dense(64, activation='sigmoid'),  # Hidden layer with Sigmoid activation
    layers.Dense(10, activation='softmax')  # Output layer with Softmax activation for classification
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5, batch_size=32)

# Evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print(f'\nTest accuracy: {test_acc}')


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.7894 - loss: 0.8677
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9443 - loss: 0.1898
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9621 - loss: 0.1297
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9730 - loss: 0.0936
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9787 - loss: 0.0727
313/313 - 1s - 3ms/step - accuracy: 0.9746 - loss: 0.0845

Test accuracy: 0.9746000170707703


In [ ]:
print(y_train)

print(y_train.shape)
print(y_test.shape)

[5 0 4 ... 5 6 8]
(60000,)
(10000,)


In [ ]:
print(x_train)

print(x_train.shape)
print(x_test.shape)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
(60000, 28

In [ ]:
# import numpy as np
# import matplotlib.pyplot as plt

# # Generate synthetic time-series data (sine wave)
# def generate_time_series(length, num_samples=1000):
#     time = np.arange(0, length)
#     sine_wave = np.sin(0.1 * time)
#     data = np.array([sine_wave + 0.05 * np.random.randn(len(sine_wave)) for _ in range(num_samples)])
#     return data

# # Data parameters
# time_series_length = 100
# num_samples = 1000


In [ ]:
# # Generate data
# data = generate_time_series(time_series_length, num_samples)


In [ ]:
# # Train-test split
# split_ratio = 0.8
# train_size = int(split_ratio * num_samples)
# train_data = data[:train_size]
# test_data = data[train_size:]



In [ ]:
# # Prepare the input and output (RNN needs input sequences and corresponding next steps)
# def create_sequences(data, seq_length):
#     X, y = [], []
#     for i in range(len(data) - seq_length):
#         X.append(data[i:i+seq_length])
#         y.append(data[i+seq_length])
#     return np.array(X), np.array(y)

# # Set sequence length
# sequence_length = 10

# # Create sequences for training and testing
# X_train, y_train = create_sequences(train_data, sequence_length)
# X_test, y_test = create_sequences(test_data, sequence_length)

# print(X_train.shape)

(790, 10, 100)


In [ ]:
# # Reshape for LSTM input (samples, time_steps, features)
# X_train = np.reshape(X_train, (X_train.shape[0], sequence_length, 100))
# X_test = np.reshape(X_test, (X_test.shape[0], sequence_length, 100))

In [ ]:
# import tensorflow as tf
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import LSTM, Dense, Dropout

# # Define the model
# model = Sequential()

# # LSTM_layer(units = 50), input_shape = (sequence_length, 1)
# model.add(LSTM(units=50, return_sequences=True, input_shape=(sequence_length, 1)))
# model.add(Dropout(0.2))  # Regularization to prevent overfitting

# # Second LSTM layer
# model.add(LSTM(units=50, return_sequences=False))
# model.add(Dropout(0.2))

# # Output layer (single value prediction for the next time step)
# model.add(Dense(units=1))

# # Compile the model
# model.compile(optimizer='adam', loss='mean_squared_error')

# # Summary of the model
# model.summary()



# # Train the model

# history = model.fit(X_train, y_train, epochs=20, batch_size=64, validation_data=(X_test, y_test))


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_2 (LSTM)                        │ (None, 10, 50)              │          10,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 10, 50)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_3 (LSTM)                        │ (None, 50)                  │          20,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 50)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 1)                   │              51 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 30,651 (119.73 KB)

 Trainable params: 30,651 (119.73 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20


ValueError: Exception encountered when calling LSTMCell.call().

Dimensions must be equal, but are 100 and 1 for '{{node sequential_6_1/lstm_2_1/lstm_cell_1/MatMul}} = MatMul[T=DT_FLOAT, grad_a=false, grad_b=false, transpose_a=false, transpose_b=false](sequential_6_1/lstm_2_1/strided_slice_2, sequential_6_1/lstm_2_1/lstm_cell_1/Cast/ReadVariableOp)' with input shapes: [?,100], [1,200].

Arguments received by LSTMCell.call():
  • inputs=tf.Tensor(shape=(None, 100), dtype=float32)
  • states=('tf.Tensor(shape=(None, 50), dtype=float32)', 'tf.Tensor(shape=(None, 50), dtype=float32)')
  • training=True

In [ ]:
# import numpy as np

# # Assume data is already a 1D array with 790,000 elements
# data = np.random.randn(790000)  # Example data

# # Parameters
# sequence_length = 10  # Number of timesteps in each sequence
# num_features = 1      # Number of features (usually 1 for univariate time series)

# # Reshape data: make sure that the total size matches
# num_sequences = data.shape[0] // sequence_length

# # Reshaping the array
# X = data[:num_sequences * sequence_length].reshape((num_sequences, sequence_length, num_features))

# # Check the shape
# print(X.shape)  # Should be (79000, 10, 1)

(79000, 10, 1)


In [ ]:
df.shape

(144, 1)

In [ ]:
X_train.shape

(93, 3, 1)

In [ ]:
print(X_train)

[[[0.01544401]
  [0.02702703]
  [0.05405405]]

 [[0.02702703]
  [0.05405405]
  [0.04826255]]

 [[0.05405405]
  [0.04826255]
  [0.03281853]]

 [[0.04826255]
  [0.03281853]
  [0.05984557]]

 [[0.03281853]
  [0.05984557]
  [0.08494207]]

 [[0.05984557]
  [0.08494207]
  [0.08494207]]

 [[0.08494207]
  [0.08494207]
  [0.06177607]]

 [[0.08494207]
  [0.06177607]
  [0.02895753]]

 [[0.06177607]
  [0.02895753]
  [0.        ]]

 [[0.02895753]
  [0.        ]
  [0.02702703]]

 [[0.        ]
  [0.02702703]
  [0.02123553]]

 [[0.02702703]
  [0.02123553]
  [0.04247104]]

 [[0.02123553]
  [0.04247104]
  [0.07142857]]

 [[0.04247104]
  [0.07142857]
  [0.05984557]]

 [[0.07142857]
  [0.05984557]
  [0.04054055]]

 [[0.05984557]
  [0.04054055]
  [0.08687258]]

 [[0.04054055]
  [0.08687258]
  [0.12741312]]

 [[0.08687258]
  [0.12741312]
  [0.12741312]]

 [[0.12741312]
  [0.12741312]
  [0.10424709]]

 [[0.12741312]
  [0.10424709]
  [0.05598456]]

 [[0.10424709]
  [0.05598456]
  [0.01930502]]

 [[0.05598456

In [ ]:
y_train.shape

(93,)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler

# Load and normalize dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv"
df = pd.read_csv(url, usecols=[1])
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(df.values.astype('float32'))

# Split and reshape dataset
train_size = int(len(dataset) * 0.67)
train, test = dataset[0:train_size, :], dataset[train_size:len(dataset), :]
look_back = 3

def create_dataset(data, look_back=1):
    X, Y = [], []
    for i in range(len(data) - look_back):
        X.append(data[i:(i + look_back), 0])
        Y.append(data[i + look_back, 0])
    return np.array(X), np.array(Y)

X_train, y_train = create_dataset(train, look_back)
X_test, y_test = create_dataset(test, look_back)
X_train = np.reshape(X_train, (X_train.shape[0], look_back, 1))
X_test = np.reshape(X_test, (X_test.shape[0], look_back, 1))

# Build and train LSTM model
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(50, input_shape=(look_back, 1)),
    tf.keras.layers.Dense(1)
])
model.compile(loss='mean_squared_error', optimizer='adam') ### since this is regression, we are using mean sqrerror
model.fit(X_train, y_train, epochs=100, batch_size=1, verbose=2)

# Evaluate the model
train_predict = scaler.inverse_transform(model.predict(X_train))
test_predict = scaler.inverse_transform(model.predict(X_test))
train_score = np.sqrt(np.mean((train_predict - scaler.inverse_transform([y_train]).T)**2))
test_score = np.sqrt(np.mean((test_predict - scaler.inverse_transform([y_test]).T)**2))
print('Train RMSE: {:.2f}, Test RMSE: {:.2f}'.format(train_score, test_score))


Epoch 1/100


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


93/93 - 2s - 17ms/step - loss: 0.0190
Epoch 2/100
93/93 - 0s - 2ms/step - loss: 0.0068
Epoch 3/100
93/93 - 0s - 2ms/step - loss: 0.0053
Epoch 4/100
93/93 - 0s - 2ms/step - loss: 0.0050
Epoch 5/100
93/93 - 0s - 3ms/step - loss: 0.0049
Epoch 6/100
93/93 - 0s - 3ms/step - loss: 0.0048
Epoch 7/100
93/93 - 0s - 3ms/step - loss: 0.0048
Epoch 8/100
93/93 - 0s - 3ms/step - loss: 0.0046
Epoch 9/100
93/93 - 0s - 3ms/step - loss: 0.0047
Epoch 10/100
93/93 - 0s - 4ms/step - loss: 0.0043
Epoch 11/100
93/93 - 0s - 3ms/step - loss: 0.0045
Epoch 12/100
93/93 - 0s - 3ms/step - loss: 0.0041
Epoch 13/100
93/93 - 0s - 2ms/step - loss: 0.0038
Epoch 14/100
93/93 - 0s - 3ms/step - loss: 0.0042
Epoch 15/100
93/93 - 0s - 3ms/step - loss: 0.0040
Epoch 16/100
93/93 - 0s - 2ms/step - loss: 0.0036
Epoch 17/100
93/93 - 0s - 2ms/step - loss: 0.0036
Epoch 18/100
93/93 - 0s - 3ms/step - loss: 0.0034
Epoch 19/100
93/93 - 0s - 3ms/step - loss: 0.0034
Epoch 20/100
93/93 - 0s - 3ms/step - loss: 0.0031
Epoch 21/100
93/93 -

1/3 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 
Train RMSE: 20.64, Test RMSE: 54.44


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler

# Load and normalize dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv"
df = pd.read_csv(url, usecols=[1])
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(df.values.astype('float32'))

# Split and reshape dataset
train_size = int(len(dataset) * 0.67)
train, test = dataset[0:train_size, :], dataset[train_size:len(dataset), :]
look_back = 3

def create_dataset(data, look_back=1):
    X, Y = [], []
    for i in range(len(data) - look_back):
        X.append(data[i:(i + look_back), 0])
        Y.append(data[i + look_back, 0])
    return np.array(X), np.array(Y)

X_train, y_train = create_dataset(train, look_back)
X_test, y_test = create_dataset(test, look_back)
X_train = np.reshape(X_train, (X_train.shape[0], look_back, 1))
X_test = np.reshape(X_test, (X_test.shape[0], look_back, 1))

# Build and train LSTM model
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(50, input_shape=(look_back, 1)),
    tf.keras.layers.Dense(1)
])
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(X_train, y_train, epochs=5, batch_size=1, verbose=2)

# Evaluate the model
train_predict = scaler.inverse_transform(model.predict(X_train))
test_predict = scaler.inverse_transform(model.predict(X_test))
train_score = np.sqrt(np.mean((train_predict - scaler.inverse_transform([y_train]).T)**2))
test_score = np.sqrt(np.mean((test_predict - scaler.inverse_transform([y_test]).T)**2))
print('Train RMSE: {:.2f}, Test RMSE: {:.2f}'.format(train_score, test_score))


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
93/93 - 5s - 58ms/step - loss: 0.0146
Epoch 2/5
93/93 - 0s - 5ms/step - loss: 0.0061
Epoch 3/5
93/93 - 0s - 2ms/step - loss: 0.0053
Epoch 4/5
93/93 - 0s - 2ms/step - loss: 0.0049
Epoch 5/5
93/93 - 0s - 3ms/step - loss: 0.0051
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 
Train RMSE: 33.43, Test RMSE: 76.85
